package dev.social.auth.accounts.mappers;

import dev.social.auth.accounts.domain.UserAccount;
import dev.social.auth.accounts.dto.AccountResponse;
import dev.social.auth.authentication.dto.LoginResponse;
import org.springframework.stereotype.Component;

/**
 * Entity to DTO translation.
 *
 * <p>Hand-written rather than generated by MapStruct. At this size the
 * annotation processor buys nothing and costs a build step plus an IDE plugin
 * every reader has to have installed - and this is the one place where
 * forgetting to map a field means leaking a password hash, so it is worth being
 * able to read the mapping directly.
 */
@Component
public class AccountMapper {

    public AccountResponse toResponse(UserAccount account) {
        return new AccountResponse(
                account.getId(),
                account.getUsername(),
                account.getEmail(),
                account.roleNames(),
                account.isEnabled(),
                account.getCreatedAt());
    }

    /**
     * Note the missing email: this summary is embedded in the login response,
     * which the frontend keeps in memory for the whole session. There is no
     * reason for an address to live there.
     */
    public LoginResponse.AuthenticatedUserSummary toSummary(UserAccount account) {
        return new LoginResponse.AuthenticatedUserSummary(
                account.getId(),
                account.getUsername(),
                account.roleNames());
    }
}
